---
title: 'About Me'
output:
  html_document:
    code_download: yes
    fontsize: 8pt
    highlight: textmate
    number_sections: no
    theme: flatly
    toc: yes
    toc_float:
      collapsed: no
---

 **I am passionate about helping people become passionate about their work.** 



## A Story About Work 
The next time you are at a social gathering, ask the people there whether they are happy with their job. Although you will sometimes find the rare individual who loves what they do, you will most frequently get responses along the lines of "I hate my job." If you probe further, you might find that every person's story about why they hate their job shares several points of similarity: The boss gets in the way of the work, and HR is a useless entity serving only to infuriate supervisors and subordinates alike. We can put a man on the moon, but we still haven't figured out how to help everyone enjoy what they do. Isn't it about time that we fixed that?



## My Philosophy 
I believe that companies can get the most out of their people when their people love what they do. However, this requires letting go of our intuitions about effective leadership strategies and adopt something new. Instead of doing what we've always done and getting what we've always got, companies can adopt bottom-up accountability systems, which replaces "Leaders" and "Followers" with "Support Specialists" and "Front-line Warriors," respectively. This inversion of the organizational chart shakes up the tired and flawed system we are so used to and makes room for people to actually love what they do. Imagine what your people could do if they no longer complained about their job? 



## My Background
I bring experience and expertise to solve problems of leadership and teamwork. I have a PhD in Social/Personality psychology, specializing in conflict and cooperation. My dissertation is on interpersonal trust, and in it I demonstrate--using a novel survey methodology that combines idiographic and nomothetic approaches--that the trust people place in another varies across the contours of the relationship. Prior to my academic career, I served honorably in the U.S. military. Throughout my military career, I was highly decorated for my leadership and teamwork behaviors. Consequently, I know *what* supports effective teamwork and leadership and *how* to implement those systems.